import d3, { select, easeLinear } from "d3";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [data, setData] = useState([24, 30, 45, 70, 26]);
  const [data2, setData2] = useState([224, 130, 345, 570, 126]);

  const svgRef = useRef(null);
  // function rectGene = ({width,margin})=>{}
  useEffect(() => {
    const svg = select(svgRef.current); // selection 객체

    const topValue = Math.max(...data2);
    console.log(topValue);
    data.forEach((data, index) => {
      svg
        .append("rect")
        .attr("height", data)
        .attr("width", 30)
        .attr("fill", "gray")
        .attr("x", 40 * index + 100) //막대 생성좌표
        .attr("y", 300 - data + 100) //막대 생성
        .transition()
        .duration(3000)
        .ease(easeLinear)
        .attr("fill", topValue === data2[index] ? "blue" : "red")
        .attr("height", data2[index])
        .attr("y", 300 - data2[index] + 100);
    });
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <>
          <svg ref={svgRef} style={{ width: "500px", height: "500px" }}></svg>
        </>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
